name: ThunderUKTeleports
main: me.corbanj_6534.TP
version: 1.0
commands:
   ttp:
      description: teleports to player
      usage: /<command>
   ttploc:
      description: Finds a players location
      usage: /<command>
   thunderuktptest:
      description: Tests the Local TP plugin
      usage: /<command> 
permissions:
    thunderuk.tp.player:
        default: false
    thunderuk.tp.findlocation:
        default: false